name: Setup Mihomo, input clash .yaml base64
description: Install mihomo (Clash Meta) and run it in the background using a YAML config.
inputs:
  config-base64:
    description: 'Base64 encoded YAML config file'
    required: false
  config-url:
    description: 'yaml链接'
    required: false
  mihomo-version:
    description: 'Version number of mihomo'
    required: false
    default: "1.18.0"
runs:
  using: "composite"
  steps:
    - name: Download mihomo
      shell: bash
      run: |
        mkdir -p .mihomo
        cd .mihomo
        wget -q https://github.com/MetaCubeX/mihomo/releases/download/v${{ inputs.mihomo-version }}/mihomo-linux-amd64-v${{ inputs.mihomo-version }}.gz
        gzip -d mihomo-linux-amd64-v${{ inputs.mihomo-version }}.gz
        mv mihomo-linux-amd64-v${{ inputs.mihomo-version }} mihomo
        chmod +x mihomo

    - name: Write YAML config file
      shell: bash
      run: |
        cd .mihomo
        if [ -n "${{ inputs.config-base64 }}" ]; then
          echo "${{ inputs.config-base64 }}" > config_enc.yaml
          cat config_enc.yaml | base64 -d > config.yaml
        elif [ -n "${{ inputs.config-url }}" ]; then
          wget -q -O config.yaml "${{ inputs.config-url }}"
        else
          echo "Error: Either config-base64 or config-url must be provided"
          exit 1
        fi

    - name: Download Web UI (Yacd)bash  
      shell: bash
      run: |
        wget https://github.com/haishanh/yacd/releases/download/v0.3.8/yacd.tar.xz
        tar -xzf yacd.tar.gz
        mv public yacd
        mkdir -p .mihomo/ui
        mv yacd/* .mihomo/ui/

    - name: Start mihomo with Web UI
      shell: bash
      run: |
        cd .mihomo
        echo "external-controller: 127.0.0.1:9090" >> config.yaml
        echo "external-ui: ui" >> config.yaml
        ./mihomo -d . -f config.yaml &
