name: Setup Mihomo, input clash .yaml base64
description: Install mihomo (Clash Meta) and run it in the background using a YAML config.
inputs:
  config-base64:
    description: 'Base64 encoded YAML config file'
    required: true
  mihomo-version:
    description: 'Version number of mihomo'
    required: false
    default: "1.18.0"
runs:
  using: "composite"
  steps:
    - name: Download mihomo
      shell: bash
      run: |
        mkdir -p .mihomo
        cd .mihomo
        wget -q https://github.com/MetaCubeX/mihomo/releases/download/v${{ inputs.mihomo-version }}/mihomo-linux-amd64-v${{ inputs.mihomo-version }}.gz
        gzip -d mihomo-linux-amd64-v${{ inputs.mihomo-version }}.gz
        mv mihomo-linux-amd64-v${{ inputs.mihomo-version }} mihomo
        chmod +x mihomo

    - name: Write YAML config file
      shell: bash
      run: |
        cd .mihomo
        echo "${{ inputs.config-base64 }}" > config_enc.yaml
        cat config_enc.yaml | base64 -d > config.yaml

    - name: Start mihomo
      shell: bash
      run: |
        cd .mihomo
        ./mihomo -d . -f config.yaml &
