name: Download and Upload Video

on:
  workflow_dispatch:  # 手动触发

jobs:
  download-and-upload:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 环境

    steps:
      # 1. 安装依赖
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          sudo curl -L https://yt-dlp.org/downloads/latest/yt-dlp -o /usr/local/bin/yt-dlp
          sudo chmod a+rx /usr/local/bin/yt-dlp
          pip install huggingface_hub

      # 2. 下载 ysptp 并设置权限
      - name: Download ysptp
        run: |
          wget https://github.com/wxhwz/ysptp/releases/download/20250313/ysptp_linux_amd64_20250313 -O ysptp
          chmod 777 ysptp

      # 3. 启动 ysptp 后台服务
      - name: Run ysptp in background
        run: |
          ./ysptp &
          sleep 10  # 等待 10 秒

      # 4. 运行 Python 脚本
      - name: Run Python script
        env:
          HUGGINGFACE_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}  # 从 GitHub Secrets 获取 Hugging Face Token
        run: |
          python3 download_and_upload.py
