name: Deploy Google Drive Download Service

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip 
          pip3 install flask requests beautifulsoup4

      - name: Start Flask server
        run: |
          python3 server.py &

      - name: Install Cloudflared
        run: |
          wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared-linux-amd64.deb

      - name: Expose Flask server with Cloudflared
        run: |
          cloudflared tunnel --url http://localhost:3000 &
          echo "Flask server is running at: http://localhost:3000"

      - name: Keep alive
        run: |
          while true; do
            echo "Service is running..."
            sleep 300
          done
